[project]
name = "concert-buddy"
version = "0.1.0"
description = "An AI assistant to help plan for attending live concerts."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.1",
    "httpx>=0.28.1",
    "openai-agents>=0.3.3",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
    "spotipy>=2.25.1",
    "uvicorn>=0.37.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
    "mypy>=1.18.2",
    "pre-commit>=4.5.1",
    "ruff>=0.13.3",
]

[tool.ruff.lint]
select = [
    "FAST",  # FastAPI
    "ASYNC", # flake8-async
    "S",     # flake8-bandit
    "B",     # flake8-bugbear
    "C4",    # flake8-comprehensions
    "LOG",   # flake8-logging
    "G",     # flake8-logging-format
    "PT",    # flake8-pytest-style
    "SIM",   # flake8-simplify
    "PTH",   # flake8-use-pathlib
    "I",     # isort
    "N",     # pep8-naming
    "E",     # pycodestyle error
    "W",     # pycodestyle warning
    "D",     # pydocstyle
    "PL",    # Pylint
]

ignore = [ # Ignore rules that conflict with Ruff formatter
    "W191",
    "E111",
    "E114",
    "E117",
    "D203",
    "D206",
    "D213",
    "D300",
]

[tool.ruff.lint.per-file-ignores]
# Ignore pydocstyle rules for all `__init__.py` files
"__init__.py" = ["D"]
