name: CI Workflow for `main` branch

on: push

jobs:
  lint-and-type-check:
    name: Run linter and type checker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Install Python
      uses: actions/setup-python@v6
      with:
        python-version-file: ".python-version

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "0.11.6"

    - name: Install the project
      run: uv sync --locked --all-groups

    - name: Run pre-commit hooks
      run: uv run pre-commit run --all-files
